owner: agx 
repo: phosh-uptime

sites:
  - name: phosh.mobi
    url: https://phosh.mobi
  - name: deb.phosh.mobi
    url: https://deb.phosh.mobi
  - name: sources.phosh.mobi
    url: https://sources.phosh.mobi
  - name: images.phosh.mobi
    url: https://images.phosh.mobi
  - name: gitlab.gnome.org
    url: https://gitlab.gnome.org/World/Phosh
  - name: Nightly build job
    url: https://source.puri.sm/guido.gunther/phosh-debs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /phosh-uptime
  logoUrl: https://phosh.mobi/images/logo.png
  theme: dark
  name: Phosh
  introTitle: "**Phosh** - A user interface for your mobile phone"
  introMessage: This status page monitors the services of [phosh.mobi](https://phosh.mobi)
  navbar:
    - title: Status
      href: /
    - title: phosh.mobi
      href: https://phosh.mobi
    - title: Uptime sources
      href: https://github.com/$OWNER/$REPO

skipDescriptionUpdate: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
